### ISSUE TITLE
Create issue-templates

### ISSUE THREAD

**Issue by astanik** [remsfal/.github#4]
**Description:**
To streamline and standardize the process of creating new issues in the "remsfal" project, the creation of issue templates should be implemented. These templates will guide contributors on providing necessary details for different types of issues (e.g., bug reports, feature requests, documentation updates).

**Tasks:**

- [x] Identify common issue types (e.g., bug reports, feature requests, and documentation improvements).
- [x] Create a markdown template for each type of issue.
- [x] Add the templates to the .github/ISSUE_TEMPLATE/ directory.
- [x] Test the templates to ensure they render correctly when creating a new issue.

**Acceptance Criteria:**

- Templates for bug reports, feature requests, and documentation updates are available.
- Templates are pre-populated with the required fields and guidelines.
- Templates are easy to use and improve the clarity of submitted issues.

**Example:**
- https://github.com/keycloak/keycloak/tree/main/.github/ISSUE_TEMPLATE

**Documentation:**
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

This issue is also related to issue [222](https://github.com/remsfal/.github/issues/3) in the [remsfal-backend](https://github.com/remsfal/remsfal-backend).

**Comment by TheoThmn** [comment]
I'd like to implement this in the course of [222](https://github.com/remsfal/.github/issues/3), please.
